Finished squadpagecard v0.1
JustinLung/fdnd pull request #18
Opened 2022-09-20 11:57 UTC by boudewijnbout

2022-09-20 12:00 UTC, DaanKorver requested changes

2022-09-20 12:00 UTC, DaanKorver commented on src/routes/+page.svelte
> +<SquadPageCard />
Kan je nog props toevoegen bij het component?

2022-09-20 13:04 UTC, boudewijnbout commented on src/routes/+page.svelte
> +<SquadPageCard />
Zijn toegevoegd.

2022-09-20 14:53 UTC, DaanKorver reviewed
Misschien een check of er een image is vannuit primsic (prop) of dat de gebruiker custom css heeft ingesteld. Iets wat we kunnen bespreken.

2022-09-20 14:54 UTC, boudewijnbout commented
> Misschien een check of er een image is vannuit primsic (prop) of dat de gebruiker custom css heeft ingesteld. Iets wat we kunnen bespreken.

Ja, ik zou niet zo goed weten hoe ik dit kan doen.

2022-09-21 07:42 UTC, JustinLung commented on src/lib/components/SquadpageCard.svelte
> +                <svg class="hashtag" version="1.1" id="Capa_2" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 490 490" style="enable-backgr
Maybe find another way to import svg's. Like making an icon component maybe?

2022-09-21 07:42 UTC, JustinLung commented on src/lib/components/SquadpageCard.svelte
> +                    <div class="arrow"></div>
maybe use a span instead of a div for semantic reasons

2022-09-21 07:42 UTC, JustinLung commented on src/lib/components/SquadpageCard.svelte
> +                <a href="">Bekijk deze squad
href is empty use # or / or link it to somewhere

2022-09-21 07:42 UTC, JustinLung commented on src/lib/components/SquadpageCard.svelte
> +        border-bottom-left-radius: 10px;
use rem instead of px

2022-09-21 07:42 UTC, JustinLung commented on src/lib/components/SquadpageCard.svelte
> +        height: 360px;
use rem instead of px, of consistency

2022-09-21 08:18 UTC, boudewijnbout commented on src/lib/components/SquadpageCard.svelte
> +                <svg class="hashtag" version="1.1" id="Capa_2" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 490 490" style="enable-backgr
Added.

2022-09-21 08:19 UTC, boudewijnbout commented on src/lib/components/SquadpageCard.svelte
> +                    <div class="arrow"></div>
Changed to span.

2022-09-21 09:01 UTC, boudewijnbout commented on src/lib/components/SquadpageCard.svelte
> +                <a href="">Bekijk deze squad
Added a #

2022-09-21 09:08 UTC, boudewijnbout commented on src/lib/components/SquadpageCard.svelte
> +        border-bottom-left-radius: 10px;
Changed possible rems to px.

2022-09-21 09:10 UTC, JustinLung approved these changes

2022-09-21 09:30 UTC, DaanKorver requested changes

2022-09-21 09:30 UTC, DaanKorver commented on src/lib/components/SquadpageCard.svelte
> +        background-image: url("../assets/images/your-tribe.avif");
Change path to relative path

2022-09-21 09:51 UTC, boudewijnbout commented on src/lib/components/SquadpageCard.svelte
> +        background-image: url("../assets/images/your-tribe.avif");
Done.

2022-09-21 09:51 UTC, JustinLung approved these changes

2022-09-21 10:04 UTC, merged